version: "2"

run:
  issues-exit-code: 1

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - ineffassign
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters: [revive]